In [83]:
from PIL import Image, ImageOps
import numpy as np
import matplotlib.pyplot as plt

image = Image.open("/home/adarsh/Downloads/Semester 1/AIKR/abc/avengers.jpg")
#image.show()
image = ImageOps.grayscale(image)
#image = image.resize(size=(400,700))
image = np.array(image)
rows = image.shape[0]
colums = image.shape[1]
print("The shape of the image is: {}".format(image.shape))
print("The number of rows and the colums in the image are: {}, {}".format(rows, colums))


#filter is of shape (3, 3)
kernel_size = 3
filter = np.ones(shape=(kernel_size, kernel_size))
filter /= filter.sum()
print("\nThe filter for the image is:\n {}".format(filter))

The shape of the image is: (933, 1400)
The number of rows and the colums in the image are: 933, 1400

The filter for the image is:
 [[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [84]:
class Image_Filter:
    def __init__(self, image, filter):
        self.image = image
        self.filter = filter
        self._imageRows = image.shape[0]
        self._imageColums = image.shape[1]
        self._filterRows = filter.shape[0]
        self._filterColums = filter.shape[1]

    def __filtering__(self, _imageRows, _imageColums, _filterRows, _filterColums, image, kernel_size):
        filtered_image = np.zeros(shape = (image.shape))
        for m in range(kernel_size//2, self._imageRows-kernel_size//2):
            for n in range(kernel_size//2, self._imageColums-kernel_size//2,):
                filtered_image[m][n] =  np.median(image[m-kernel_size//2:m+kernel_size//2+1, n-kernel_size//2: n+kernel_size//2+1])
        return filtered_image

In [85]:
imageObject = Image_Filter(image, filter)

filtered_image  = Image.fromarray(imageObject.__filtering__(imageObject._imageRows, imageObject._imageColums, imageObject._filterRows, imageObject._filterColums, image, kernel_size))

In [90]:
filtered_image.show()


(eog:74883): Gtk-WARNING **: 19:50:40.989: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
